name: Build & publish Docker image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@stable

      - name: Build and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kdrag0n/pyrobud:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
